import Head from 'next/head';
import styles from './index.module.scss';
import Image from 'next/image';
import Map from '@components/map';

// THINKING: are "CONFIDENT" and "PRAGMATIC COMPREHENSIVE" be the same components, and use the props to control left or right
// THINKING: are the "We do real work, not just to put up empty promises" and "Map" be the same as well
export default function About() {

    const defaultProps = {
        center: {
          lat: 10.99835602,
          lng: 77.01502627
        },
        zoom: 11
    };

    return (
        <div className={styles.aboutPageMainContainer}>
            <Head>
                <title>About Us - ECMA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.heroSectionContainer}>
                <Image
                    className={styles.heroImage}
                    src='/aesop.jpeg'
                    alt='aesop'
                    fill
                />
                <h1 className={styles.heroTitle}>PROFESSIONAL HIGH-END</h1>
                {/* TODO: component - Card, and migrate the header navbar with using the Card component */}
                {/* FIXME: typo */}
                <div className={styles.heroDescriptonContainer}>
                    <div className={styles.heroDescriptionText}>
                    EDMC offers project management, consulting and contracting services in a wide range of interior fitting out projects, including office premises, retail outlets, residences, hotels and art galleries.
                    </div>
                </div>
            </div>
            <div className={styles.confidentContainer}>
                <h1 className={styles.confidentHeader}>CONFIDENT</h1>
                <div className={styles.confidentImageContainer}>
                    <Image
                        className={styles.confidentImage}
                        src='/confident.png'
                        alt='confident'
                        fill
                    />
                </div>
                <div className={styles.confidentDiv}>
                    Fitting out contracting services and projects including carpentry, metal works, plumbing and drainage, electrical works, air-conditioning works, cement works, painting, aluminum works, glass partition, signage and graphic production.
                </div>
            </div>
            <div className={styles.realWorkContainer}>
                <h1 className={styles.realWorkHeader}>We do real work, not just to put up empty promises</h1>
                <div className={styles.realWorkImageContainer}>
                    <Image
                        className={styles.realWorkImage}
                        src='/realWork.png'
                        alt='real work'
                        fill
                    />
                </div>
            </div>
            <div className={styles.pragmaticContainer}>
                <h1 className={styles.pragmaticHeader}>PRAGMATIC</h1>
                <div className={styles.pragmaticDiv}>
                    COMPREHENSIVE interior fitting out contracting services and projects including carpentry, metal works, plumbing and drainage, electrical works, air-conditioning works, cement works, painting, aluminum works, glass partition, signage and graphic production.
                </div>
                <div className={styles.pragmaticImageContainer}>
                    <Image
                        className={styles.pragmaticImage}
                        src='/pragmatic.png'
                        alt='pragmatic'
                        fill
                    />
                </div>

            </div>
            <div id='location' className={styles.locationContainer}>
                <h1 className={styles.locationHeader}>We locate here</h1>
                <div className={styles.locationMapContainer}>
                    <Map longitude={114.1904734} latitude={22.3151962} />
                </div>
            </div>
        </div>
    )
}