import Head from 'next/head';
import styles from './index.module.scss';
import Image from 'next/image';
import Map from '@components/map';

export default function About() {

    const defaultProps = {
        center: {
          lat: 10.99835602,
          lng: 77.01502627
        },
        zoom: 11
    };

    return (
        <div className={styles.aboutPageMainContainer}>
            <Head>
                <title>About Us - ECMA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.heroSectionContainer}>
                <Image
                    className={styles.heroImage}
                    src='/aesop.jpeg'
                    alt='aesop'
                    fill
                />
                <h1 className={styles.heroTitle}>PROFESSIONAL HIGH-END</h1>
                <div className={styles.heroDescriptonContainer}>
                    <div className={styles.heroDescriptionText}>
                        Some text Some text Some text Some text Some text Some text Some text Some text Some text
                    </div>
                </div>
            </div>
            <div className={styles.confidentContainer}>
                <h1 className={styles.confidentHeader}>CONFIDENT</h1>
                <div className={styles.confidentDiv}> confident Div</div>
                <Image
                    className={styles.confidentImage}
                    src='/aesop.jpeg'
                    alt='aesop'
                    width={650}
                    height={500}
                />
                <div className={styles.confidentDiv}> confident Div</div>
            </div>
            <div className={styles.realWorkContainer}>
                <h1>We do real work, not just to put up empty promises</h1>
                <Image
                    className={styles.confidentImage}
                    src='/aesop.jpeg'
                    alt='aesop'
                    width={650}
                    height={500}
                />
            </div>
            <div className={styles.pragmaticContainer}>
                <h1 className={styles.pragmaticHeader}>Pragmatic</h1>
                <div className={styles.pragmaticDiv}>
                    Pragmatic Div
                </div>
                <Image
                    className={styles.pragmaticImage}
                    src='/aesop.jpeg'
                    alt='aesop'
                    width={650}
                    height={500}
                />
            </div>
            <div id='location' className={styles.locationContainer}>
                <h1>We locate here</h1>
                <div className={styles.locationMapContainer}>
                    <Map longitude={114.1882847} latitude={22.3151962} />
                </div>
            </div>
        </div>
    )
}