import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: '400px', backgroundColor: 'black' }}>Hello</div>
      <div style={{ height: '400px', backgroundColor: 'black' }}>Hello</div>
      <div style={{ height: '400px' }}>Hello</div>
      <div style={{ height: '400px' }}>Hello</div>
      <div style={{ height: '400px' }}>Hello</div>
      <div style={{ height: '400px' }}>Hello</div>
    </>
  )
}
