import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from './index.module.scss';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

const galleryContent = [
  {
    name: 'First Picture',
    description: 'First Page Description',
    img: '/aesop.jpeg',
    imgAlt: 'Aesop'
  },
  {
    name: 'Second Picture',
    description: 'Second Page Description',
    img: '/aesop2.jpeg',
    imgAlt: 'Aesop 2'
  },
];

export default function Home() {

  const [galleryIndex, setGalleryIndex] = useState<number>(0);

  const getNewGalleryIndex = (isNext: boolean) => {
    if (isNext) {
      if (galleryIndex + 1 >= galleryContent.length) {
        setGalleryIndex(0)
      } else {
        setGalleryIndex(galleryIndex + 1);
      }
    } else {
      if (galleryIndex - 1 < 0) {
        setGalleryIndex(galleryContent.length - 1)
      } else {
        setGalleryIndex(galleryIndex - 1);
      }
    }
  }

  return (
    <>
      <Head>
        <title>ECMA Website Revamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.galleryImageContainer}>
        <Image
          key={galleryIndex}
          className={styles.galleryImage}
          src={galleryContent[galleryIndex]['img']}
          alt={galleryContent[galleryIndex]['imgAlt']}
          fill
        />
      </div>
      <div className={styles.galleryCardContainer}>
        <h1 className={styles.galleryCardTitle}>{galleryContent[galleryIndex]['name']}</h1>
        <div className={styles.galleryCardDescriptionContainer}>
          <div>
            {galleryContent[galleryIndex]['description']}
          </div>
          <div className={styles.space} />
          <button className={styles.galleryDescriptionViewButton}>
            View
          </button>
        </div>
        <div className={styles.galleryScrollContainer}>
          <button onClick={() => getNewGalleryIndex(false)}>Previous</button>
          <div className={styles.space} />
          <button onClick={() => getNewGalleryIndex(true)}>Next</button>
        </div>
      </div>

    </>
  )
}
